language: node_js
node_js:
  - "iojs-v1.6.0"
before_script:
  - cp "lib/config.example.js" "lib/config.js"
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
notifications:
  irc:
    channels:
      - "irc.esper.net#crafatar"
    skip_join: true
services:
  - redis-server
cache:
  directories:
    - node_modules